/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class formulario extends javax.swing.JFrame {
    conectar conecto;
    PreparedStatement ps;
    ResultSet rs;
   
    private static Connection conn;
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/dbpanalera";
    
    public formulario(){
        initComponents();
    }
    
   public Connection getConnection(){
       conn = null;
        try{
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, pass);
            if (conn != null) {
                System.out.println("La conexión se establecio bien con la DB");
                
            }
        }catch (ClassNotFoundException | SQLException e) {
                System.out.println("Error al conectar con la DB" + e);
        
        }
      
       return conn;
   }
    
   public void desconectar (){
       conn = null;
       if (conn == null){
           System.out.println("Se desconecto de la DB");
       }
       
   }
   
   public void borrarCajas(){
       cajaNom.setText(null);
       cajaTel.setText(null);
       cajaDir.setText(null);
       cajaProd.setText(null);
       cajaUni.setText(null);
       cajaCup.setText(null);
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jllogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cajaNom = new javax.swing.JTextField();
        cajaTel = new javax.swing.JTextField();
        cajaDir = new javax.swing.JTextField();
        cajaProd = new javax.swing.JTextField();
        cajaUni = new javax.swing.JTextField();
        cajaCup = new javax.swing.JTextField();
        BConectar = new javax.swing.JButton();
        BDesconectar = new javax.swing.JButton();
        BComprar = new javax.swing.JButton();
        jlfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estafue.PNG"))); // NOI18N
        jllogo.setText("jLabel1");
        getContentPane().add(jllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel1.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        jLabel1.setText("TODO PARA SU BEBE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("Teléfono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("Unidades");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("Cupón");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        cajaNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cajaNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 220, -1));

        cajaTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cajaTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 220, -1));

        cajaDir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cajaDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 220, -1));

        cajaProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cajaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 220, -1));

        cajaUni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cajaUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 220, -1));

        cajaCup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cajaCup, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 220, -1));

        BConectar.setBackground(new java.awt.Color(255, 255, 51));
        BConectar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        BConectar.setText("CONECTAR");
        BConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConectarActionPerformed(evt);
            }
        });
        getContentPane().add(BConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        BDesconectar.setBackground(new java.awt.Color(255, 255, 51));
        BDesconectar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        BDesconectar.setText("DESCONECTAR");
        BDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(BDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        BComprar.setBackground(new java.awt.Color(255, 255, 51));
        BComprar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        BComprar.setText("COMPRAR");
        BComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BComprarActionPerformed(evt);
            }
        });
        getContentPane().add(BComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jlfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-diaper-diaper-pull-up-pants-main-picture-image_192673.jpg"))); // NOI18N
        getContentPane().add(jlfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTelActionPerformed

    private void BConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConectarActionPerformed
        conecto = new conectar ();
        Connection reg = conecto.getConnection();
    }//GEN-LAST:event_BConectarActionPerformed

    private void BDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDesconectarActionPerformed
        conecto.desconectar();
    }//GEN-LAST:event_BDesconectarActionPerformed

    private void BComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BComprarActionPerformed
        Connection conn = null;
        try {
            conn = getConnection();
            ps = conn.prepareStatement("INSERT INTO compra (nombre, telefono, direccion, fechareg, producto, unidades, cupon) VALUES (?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, cajaNom.getText());
            ps.setString(2, cajaTel.getText());
            ps.setString(3, cajaDir.getText());
            ps.setDate(4, Date.valueOf(LocalDate.now()));
            ps.setString(5, cajaProd.getText());
            ps.setString(6, cajaUni.getText());
            ps.setString(7, cajaCup.getText());
            int result =   ps.executeUpdate();
            
            if(result > 0){
                JOptionPane.showMessageDialog(null, "Los Datos fueron enviados correctamente");
                borrarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "Los Datos no fueron enviados correctamente");
            }
            
            conn.close();
      
        } catch (Exception e) {
            System.out.println(e);
        }
              
    }//GEN-LAST:event_BComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComprar;
    private javax.swing.JButton BConectar;
    private javax.swing.JButton BDesconectar;
    private javax.swing.JTextField cajaCup;
    private javax.swing.JTextField cajaDir;
    private javax.swing.JTextField cajaNom;
    private javax.swing.JTextField cajaProd;
    private javax.swing.JTextField cajaTel;
    private javax.swing.JTextField cajaUni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlfondo;
    private javax.swing.JLabel jllogo;
    // End of variables declaration//GEN-END:variables
}
